export { default as Header } from "./Header";
export { default as WhatsappButton } from "./WhatsappButton";
export { default as Hero } from "./Hero";
export { default as Services } from "./Services";
export { default as About } from "./About";
export { default as Pricing } from "./Pricing";
export { default as Contact } from "./Contact";
export { default as Testimonials } from "./Testimonials";
export { default as Footer } from "./Footer";